eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    r:
      path: /r/**
      serviceId: eureka-ribbon-client
    f:
      path: /f/**
      serviceId: eureka-feign-client
